//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 10:44:08 AM CET 
//


package jaxb.persons.solution.ch.bfh.persons;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.bfh.persons package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Persons_QNAME = new QName("http://www.bfh.ch/persons/", "persons");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.bfh.persons
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonsType }
     * 
     */
    public PersonsType createPersonsType() {
        return new PersonsType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bfh.ch/persons/", name = "persons")
    public JAXBElement<PersonsType> createPersons(PersonsType value) {
        return new JAXBElement<PersonsType>(_Persons_QNAME, PersonsType.class, null, value);
    }

}
